name: Check PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: semver
        uses: ./
        with:
          always: true
          push-tag: true
          verbose: true

      - name: Generate Changelog
        run: |
          echo "changed: ${{ steps.semver.outputs.changed }}"
          echo "current: ${{ steps.semver.outputs.current }}"
          echo "next: ${{ steps.semver.outputs.next }}"
