name: Publish

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: semver
        uses: ./
        with:
          always: true
          push-tag: true
          verbose: true

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5.3.0
        with:
          owner: bencatlab
          fromTag: ${{ steps.semver.outputs.current }}
          toTag: ${{ steps.semver.outputs.next }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          body_path: ${{ steps.changelog.outputs.changelog }}-CHANGELOG.txt
          tag_name: ${{ steps.semver.outputs.next }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle Release Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          MAJOR=$(echo "${{ steps.semver.outputs.next }}" | cut -d. -f1)

          git tag -f $MAJOR ${{ steps.semver.outputs.next }}
          git push --force origin v$MAJOR
